#!/usr/bin/env bash
# discover-otel-schema.sh - Capture native Claude Code OTEL signals for live verification.
#
# The authoritative schema is docs/otel-native-schema.md (from binary analysis).
# This script captures live data to verify and supplement that analysis.
#
# Runs an OTEL collector in discovery mode (no filelog/warden receiver) to
# isolate what Claude Code itself emits. After a user-driven session, parses
# the captured JSONL and writes a discovery report.
#
# Requires: docker (or podman), jq

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DATA_DIR="/tmp/claude-otel-discovery"
OUTPUT_DOC="$ROOT_DIR/docs/otel-discovery-report.md"
COLLECTOR_CONFIG="$ROOT_DIR/monitoring/otel-collector-discovery.yaml"
CONTAINER_NAME="warden-otel-discovery"

# Detect container runtime
RUNTIME="docker"
if ! command -v docker &>/dev/null; then
    if command -v podman &>/dev/null; then
        RUNTIME="podman"
    else
        echo "Error: docker or podman required" >&2
        exit 1
    fi
fi

command -v jq &>/dev/null || { echo "Error: jq required" >&2; exit 1; }

# Clean up previous runs
rm -rf "$DATA_DIR"
mkdir -p "$DATA_DIR"
touch "$DATA_DIR/metrics.jsonl" "$DATA_DIR/logs.jsonl" "$DATA_DIR/traces.jsonl"

echo "=== OTEL Discovery Mode ==="
echo "Data dir:  $DATA_DIR"
echo "Config:    $COLLECTOR_CONFIG"
echo ""

# Start collector
echo "Starting OTEL collector (discovery mode)..."
"$RUNTIME" run -d --rm \
    --name "$CONTAINER_NAME" \
    --network host \
    -v "$COLLECTOR_CONFIG:/etc/otel-collector-config.yaml:ro" \
    -v "$DATA_DIR:/data" \
    otel/opentelemetry-collector-contrib:latest \
    --config=/etc/otel-collector-config.yaml

echo "Collector running as '$CONTAINER_NAME'"
echo ""
echo "------------------------------------------------------------"
echo "Now run a Claude Code session for 2+ minutes."
echo "Exercise: multiple tools, a subagent, deny a tool, compact."
echo ""
echo "Required env vars (set before launching Claude Code):"
echo "  export CLAUDE_CODE_ENABLE_TELEMETRY=true"
echo "  export OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318"
echo ""
echo "Optional (more data):"
echo "  export OTEL_LOG_TOOL_CONTENT=true     # PII: tool I/O in spans"
echo "  export OTEL_LOG_USER_PROMPTS=true     # PII: raw prompts in spans"
echo "------------------------------------------------------------"
echo ""
read -rp "Press Enter when done..."

# Stop collector
echo ""
echo "Stopping collector..."
"$RUNTIME" stop "$CONTAINER_NAME" 2>/dev/null || true

# Check for data
METRICS_LINES=$(wc -l < "$DATA_DIR/metrics.jsonl" 2>/dev/null || echo 0)
LOGS_LINES=$(wc -l < "$DATA_DIR/logs.jsonl" 2>/dev/null || echo 0)
TRACES_LINES=$(wc -l < "$DATA_DIR/traces.jsonl" 2>/dev/null || echo 0)

echo ""
echo "Captured:"
echo "  Metrics: $METRICS_LINES lines"
echo "  Logs:    $LOGS_LINES lines"
echo "  Traces:  $TRACES_LINES lines"
echo ""

# Parse and generate schema doc
echo "Generating schema documentation..."

{
cat << 'HEADER'
# Claude Code Native OTEL Schema

> Auto-generated by `scripts/discover-otel-schema.sh`
> Re-run after Claude Code updates to detect new signals.

## Known Metrics (from Grafana dashboard queries)

| Metric | Type | Notes |
|--------|------|-------|
| `claude_code_cost_usage_USD_total` | counter | Session cost in USD |
| `claude_code_token_usage_tokens_total` | counter | Token consumption (labels: type) |
| `claude_code_active_time_seconds_total` | counter | Wall-clock active time |
| `claude_code_session_count_total` | counter | Session count |

## Discovered Metrics

HEADER

if (( METRICS_LINES > 0 )); then
    echo "| Metric Name | Type | Unit | Labels |"
    echo "|-------------|------|------|--------|"

    # Extract unique metric names, types, units, and label keys
    jq -r '
        .resourceMetrics[]?.scopeMetrics[]?.metrics[]? |
        {
            name: .name,
            type: (if .sum then "sum" elif .gauge then "gauge" elif .histogram then "histogram" elif .summary then "summary" else "unknown" end),
            unit: (.unit // ""),
            labels: (
                (if .sum then .sum.dataPoints[]? elif .gauge then .gauge.dataPoints[]? elif .histogram then .histogram.dataPoints[]? else empty end) |
                .attributes // [] | map(.key) | sort | join(", ")
            )
        } |
        "| `\(.name)` | \(.type) | \(.unit) | \(.labels) |"
    ' "$DATA_DIR/metrics.jsonl" 2>/dev/null | sort -u || echo "*No metrics captured.*"
    echo ""

    echo "### Resource Attributes (Metrics)"
    echo '```'
    jq -r '.resourceMetrics[]?.resource?.attributes[]? | "\(.key) = \(.value | tostring)"' \
        "$DATA_DIR/metrics.jsonl" 2>/dev/null | sort -u || echo "(none)"
    echo '```'
else
    echo "*No metrics captured. Ensure Claude Code OTEL export is enabled.*"
fi

cat << 'SECTION'

## Discovered Logs

SECTION

if (( LOGS_LINES > 0 )); then
    echo "### Log Severities"
    echo '```'
    jq -r '.resourceLogs[]?.scopeLogs[]?.logRecords[]?.severityText // "UNSET"' \
        "$DATA_DIR/logs.jsonl" 2>/dev/null | sort | uniq -c | sort -rn || echo "(none)"
    echo '```'
    echo ""

    echo "### Log Attribute Keys"
    echo '```'
    jq -r '.resourceLogs[]?.scopeLogs[]?.logRecords[]?.attributes[]?.key' \
        "$DATA_DIR/logs.jsonl" 2>/dev/null | sort -u || echo "(none)"
    echo '```'
    echo ""

    echo "### Log Bodies (sample)"
    echo '```'
    jq -r '.resourceLogs[]?.scopeLogs[]?.logRecords[]?.body?.stringValue // empty' \
        "$DATA_DIR/logs.jsonl" 2>/dev/null | head -20 || echo "(none)"
    echo '```'
    echo ""

    echo "### Resource Attributes (Logs)"
    echo '```'
    jq -r '.resourceLogs[]?.resource?.attributes[]? | "\(.key) = \(.value | tostring)"' \
        "$DATA_DIR/logs.jsonl" 2>/dev/null | sort -u || echo "(none)"
    echo '```'
else
    echo "*No logs captured.*"
fi

cat << 'SECTION'

## Discovered Traces

SECTION

if (( TRACES_LINES > 0 )); then
    echo "### Span Names"
    echo '```'
    jq -r '.resourceSpans[]?.scopeSpans[]?.spans[]?.name' \
        "$DATA_DIR/traces.jsonl" 2>/dev/null | sort | uniq -c | sort -rn || echo "(none)"
    echo '```'
    echo ""

    echo "### Span Kinds"
    echo '```'
    jq -r '.resourceSpans[]?.scopeSpans[]?.spans[]?.kind // "UNSPECIFIED"' \
        "$DATA_DIR/traces.jsonl" 2>/dev/null | sort | uniq -c | sort -rn || echo "(none)"
    echo '```'
    echo ""

    echo "### Span Attribute Keys"
    echo '```'
    jq -r '.resourceSpans[]?.scopeSpans[]?.spans[]?.attributes[]?.key' \
        "$DATA_DIR/traces.jsonl" 2>/dev/null | sort -u || echo "(none)"
    echo '```'
    echo ""

    echo "### Resource Attributes (Traces)"
    echo '```'
    jq -r '.resourceSpans[]?.resource?.attributes[]? | "\(.key) = \(.value | tostring)"' \
        "$DATA_DIR/traces.jsonl" 2>/dev/null | sort -u || echo "(none)"
    echo '```'
else
    echo "*No traces captured.*"
fi

cat << 'SECTION'

## Signal Gap Analysis

### Hooks provide / OTEL does not

| Signal | Hook Source | Notes |
|--------|-----------|-------|
| Tool output size (bytes/lines) | `post-tool-use` | `tool_output_size` event |
| Output truncation events | `post-tool-use` | `truncated` event with rule |
| Blocked tool calls | `pre-tool-use` | `blocked` event with reason |
| Quiet override tracking | `pre-tool-use` | Command modification events |
| Subagent lifecycle | `subagent-start/stop` | Start/stop/duration/bytes |
| Budget enforcement | `subagent-start` | Token budget checks |
| System reminder stripping | `post-tool-use` | Removes `<system-reminder>` blocks |

### Overlap Analysis (hooks reconstruct / OTEL already has)

| Signal | Hook Source | Native OTEL Source | Can hooks stop? |
|--------|-----------|-------------------|-----------------|
| Tool latency | pre+post-tool-use file correlation | *check traces* | Pending discovery |
| Session cost | statusline scraping | `claude_code_cost_usage_USD_total` | Yes (metrics) |
| Token counts | estimated (bytes/3.5) | `claude_code_token_usage_tokens_total` | Yes (metrics) |
| Active time | statusline scraping | `claude_code_active_time_seconds_total` | Yes (metrics) |

## Env Var Impact

| Variable | Expected Effect | Observed |
|----------|----------------|----------|
| `OTEL_EXPORTER_OTLP_ENDPOINT` | Direct OTLP export | *fill after discovery* |
| `OTEL_LOG_TOOL_DETAILS` | Additional tool detail attributes | *fill after discovery* |
| `OTEL_TRACES_SAMPLER` | Trace sampling config | *fill after discovery* |
| `OTEL_SERVICE_NAME` | Override service.name resource attr | *fill after discovery* |

SECTION

} > "$OUTPUT_DOC"

echo "Schema doc written to: $OUTPUT_DOC"
echo ""
echo "Raw data preserved at: $DATA_DIR"
echo "Inspect manually with:"
echo "  jq . $DATA_DIR/metrics.jsonl | less"
echo "  jq . $DATA_DIR/logs.jsonl | less"
echo "  jq . $DATA_DIR/traces.jsonl | less"
