use clap::Parser;
use std::net::SocketAddr;
use std::path::PathBuf;
use tokio::signal;
use tracing::info;

mod compress;
mod config;
mod db;
mod handlers;
mod observability;
mod router;
mod security;
mod server;
mod types;

#[derive(Parser)]
#[command(name = "warden-daemon", about = "HTTP hook daemon for claude-warden")]
struct Cli {
    /// Port to listen on
    #[arg(long, default_value = "7483", env = "WARDEN_PORT")]
    port: u16,

    /// SQLite database path
    #[arg(long, env = "WARDEN_DB")]
    db: Option<PathBuf>,

    /// Policy file path
    #[arg(long, env = "WARDEN_POLICY")]
    policy: Option<PathBuf>,

    /// Config file path (warden.toml, generated by install.sh)
    #[arg(long, env = "WARDEN_CONFIG")]
    config: Option<PathBuf>,

    /// PID file path
    #[arg(long, env = "WARDEN_PIDFILE")]
    pidfile: Option<PathBuf>,

    /// Auto-exit after N seconds of no requests (0 = never)
    #[arg(long, default_value = "300", env = "WARDEN_IDLE_TIMEOUT")]
    idle_timeout: u64,

    /// JSONL events file path (backward compatibility with v1 dashboards)
    #[arg(long, env = "WARDEN_EVENTS_FILE")]
    events_file: Option<PathBuf>,
}

#[tokio::main(flavor = "current_thread")]
async fn main() -> anyhow::Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "warden_daemon=info".into()),
        )
        .with_target(false)
        .init();

    let cli = Cli::parse();

    // Resolve paths (defaults under ~/.claude/.warden/)
    let warden_dir = dirs::home_dir()
        .unwrap_or_default()
        .join(".claude")
        .join(".warden");

    let db_path = cli.db.unwrap_or_else(|| warden_dir.join("state.db"));
    let policy_path = cli
        .policy
        .unwrap_or_else(|| warden_dir.join("policy.toml"));
    let config_path = cli
        .config
        .unwrap_or_else(|| warden_dir.join("warden.toml"));
    let events_path = cli.events_file.unwrap_or_else(|| {
        dirs::home_dir()
            .unwrap_or_default()
            .join(".claude")
            .join(".statusline")
            .join("events.jsonl")
    });

    // Ensure events directory exists
    if let Some(parent) = events_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    // Write PID file
    if let Some(ref pidfile) = cli.pidfile {
        if let Some(parent) = pidfile.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let pid = std::process::id();
        tokio::fs::write(pidfile, pid.to_string()).await?;
        info!("PID {} written to {:?}", pid, pidfile);
    }

    // Initialize
    let config = config::Config::load(&config_path, &policy_path)?;
    let database = db::Database::open(&db_path)?;
    let parser = security::bash_validator::BashValidator::new()?;

    // Build app state
    let state = server::AppState::new(config, database, parser, events_path);

    // Start server
    let addr = SocketAddr::from(([127, 0, 0, 1], cli.port));
    info!("warden-daemon listening on {}", addr);

    let app = server::build_router(state.clone());

    let listener = tokio::net::TcpListener::bind(addr).await?;

    // Graceful shutdown on SIGINT/SIGTERM or idle timeout
    let idle_timeout = cli.idle_timeout;
    axum::serve(listener, app)
        .with_graceful_shutdown(async move {
            let ctrl_c = signal::ctrl_c();

            #[cfg(unix)]
            let sigterm = async {
                signal::unix::signal(signal::unix::SignalKind::terminate())
                    .expect("failed to install SIGTERM handler")
                    .recv()
                    .await;
            };

            #[cfg(not(unix))]
            let sigterm = std::future::pending::<()>();

            tokio::select! {
                _ = ctrl_c => info!("received SIGINT, shutting down"),
                _ = sigterm => info!("received SIGTERM, shutting down"),
                _ = state.wait_for_idle(idle_timeout) => info!("idle timeout, shutting down"),
                _ = state.wait_for_shutdown_signal() => info!("shutdown requested via /shutdown"),
            }
        })
        .await?;

    // Cleanup PID file
    if let Some(ref pidfile) = cli.pidfile {
        let _ = tokio::fs::remove_file(pidfile).await;
    }

    info!("warden-daemon stopped");
    Ok(())
}
